# Generated by Django 5.2.6 on 2026-09-17 05:26

import accounts.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_member_handle_unique'),
        ('content', '0003_sociallink_members_only'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, help_text="The end of the event's address. Made from the title if left blank, and fixed once the event exists, so links already shared keep working.", max_length=80, unique=True)),
                ('summary', models.CharField(help_text='One or two sentences, shown in the list of events.', max_length=240)),
                ('description', models.TextField(blank=True, default='', help_text='Optional. Anything else people should know.')),
                ('starts_at', models.DateTimeField(db_index=True)),
                ('ends_at', models.DateTimeField()),
                ('location', models.CharField(blank=True, default='', help_text="Where to go, for example 'Engineering building, room 301'. Shown to everyone who can see the event.", max_length=160)),
                ('online_url', models.URLField(blank=True, default='', help_text='A video call link, if the event is online. Only shown to people who have a place — never to people on the waiting list or to anyone else.', validators=[accounts.validators.validate_web_url], verbose_name='online link')),
                ('capacity', models.PositiveIntegerField(blank=True, help_text='How many places. Leave blank for no limit. When it is full, new sign-ups join a waiting list and move up automatically as places free. Raising it gives places to the waiting list straight away; lowering it never takes a place from anyone who already has one.', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('registration_closes_at', models.DateTimeField(blank=True, help_text='Optional. Leave blank to keep registration open until the event starts.', null=True)),
                ('visibility', models.CharField(choices=[('public', 'Anyone can see it'), ('members', 'Only approved members can see it')], default='public', max_length=10)),
                ('audience', models.CharField(choices=[('members', 'Approved members'), ('accounts', 'Anyone with a confirmed account, including people awaiting review')], default='members', help_text="'Anyone with a confirmed account' suits a newcomers' session that people should be able to attend before their membership is reviewed.", max_length=10, verbose_name='who can register')),
                ('status', models.CharField(choices=[('draft', 'Draft — only the leadership team can see it'), ('published', 'Published'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=10)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(blank=True, help_text="Which of the community's activities this is, if any. Used to group events on profiles and on the activity's own page.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='content.activity')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['starts_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('going', 'Has a place'), ('waitlist', 'On the waiting list'), ('cancelled', 'Cancelled')], db_index=True, default='going', max_length=10)),
                ('role', models.CharField(choices=[('attendee', 'Took part'), ('presenter', 'Presented'), ('organiser', 'Organised'), ('helper', 'Helped run it')], default='attendee', max_length=10)),
                ('attended', models.BooleanField(blank=True, help_text="Marked by the leadership team after the event. Only events marked as attended appear on a member's profile.", null=True)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='events.event')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='accounts.member')),
            ],
            options={
                'verbose_name': 'registration',
                'verbose_name_plural': 'registrations',
                'ordering': ['joined_at', 'pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='event_ends_after_it_starts'),
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['event', 'status', 'joined_at'], name='registration_queue'),
        ),
        migrations.AddConstraint(
            model_name='registration',
            constraint=models.UniqueConstraint(fields=('event', 'member'), name='one_registration_per_member_per_event'),
        ),
    ]
