# Generated by Django 5.2.6 on 2026-08-29 12:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent', models.CharField(choices=[('join', 'Membership application'), ('question', 'Question')], default='join', max_length=16)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=160)),
                ('student', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('soon', 'Starting soon'), ('', 'Not answered')], default='', max_length=8)),
                ('student_id', models.CharField(blank=True, default='', max_length=40, verbose_name='student ID')),
                ('interests', models.JSONField(blank=True, default=list)),
                ('message', models.TextField(blank=True, default='', max_length=2000)),
                ('consented_to_contact', models.BooleanField(default=False)),
                ('accepted_documents', models.BooleanField(default=False, help_text='Accepted the community rules, terms and privacy notice.')),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewing', 'Being reviewed'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('spam', 'Spam')], db_index=True, default='new', max_length=12)),
                ('review_notes', models.TextField(blank=True, default='', help_text='Internal. Never emailed.')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmation_sent', models.BooleanField(default=False)),
                ('notification_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'application',
                'verbose_name_plural': 'applications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['intent', 'status'], name='application_intent_558c58_idx')],
            },
        ),
    ]
