# Generated by Django 5.2.6 on 2026-09-04 09:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(help_text="How this person's name appears to the rest of the community.", max_length=120)),
                ('student', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('soon', 'Starting soon'), ('', 'Not answered')], default='', max_length=8)),
                ('student_id', models.CharField(blank=True, default='', max_length=40, verbose_name='student ID')),
                ('interests', models.JSONField(blank=True, default=list)),
                ('bio', models.TextField(blank=True, default='', help_text='A short introduction. Optional, and shown only to other members.', max_length=600)),
                ('github_url', models.URLField(blank=True, default='')),
                ('linkedin_url', models.URLField(blank=True, default='')),
                ('accepted_documents', models.BooleanField(default=False)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Awaiting review'), ('active', 'Member'), ('paused', 'Paused'), ('removed', 'Removed')], db_index=True, default='pending', max_length=10)),
                ('notes', models.TextField(blank=True, default='', help_text='Internal. Never emailed.')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'member',
                'verbose_name_plural': 'members',
                'ordering': ['-created_at'],
            },
        ),
    ]
