# Generated by Django 5.2.6 on 2026-08-29 12:58

import content.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(default=True, help_text='Untick to hide this from the site.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers come first.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('cadence', models.CharField(help_text='For example "Weekly" or "Once a term".', max_length=60)),
                ('cadence_is_primary', models.BooleanField(default=False, help_text='Show the cadence tag in the darker style.')),
                ('extra_tag', models.CharField(blank=True, default='', help_text='Optional second tag, e.g. "Member-run".', max_length=40)),
                ('summary', models.TextField(help_text='Shown on the activities index and used as the meta description.')),
                ('body', models.TextField(blank=True, default='', help_text='Paragraphs for the index entry. One per blank-line-separated block.')),
                ('index_bullets', content.models.BulletsField(blank=True, default='', help_text='One bullet shown on the index page per line. Blank lines are ignored.')),
            ],
            options={
                'verbose_name': 'activity',
                'verbose_name_plural': 'activities',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(default=True, help_text='Untick to hide this from the site.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers come first.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=40)),
                ('value', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'home page fact',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FaqEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(default=True, help_text='Untick to hide this from the site.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers come first.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(max_length=160)),
                ('anchor', models.SlugField(blank=True, max_length=60)),
                ('answer', models.TextField(help_text='One paragraph per blank-line-separated block.')),
            ],
            options={
                'verbose_name': 'question',
                'verbose_name_plural': 'questions',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HomeCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(default=True, help_text='Untick to hide this from the site.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers come first.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=80)),
                ('body', models.TextField()),
                ('icon', models.CharField(choices=[('book', 'Open book'), ('brackets', 'Code brackets'), ('network', 'Connected people'), ('screen', 'Screen')], default='book', max_length=12)),
            ],
            options={
                'verbose_name': 'home page card',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InterestArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(default=True, help_text='Untick to hide this from the site.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers come first.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('subtitle', models.CharField(blank=True, default='', max_length=120)),
                ('bullets', content.models.BulletsField(help_text='One line per line. Blank lines are ignored.')),
                ('on_application_form', models.BooleanField(default=True, help_text='Offer this as a tick box on the join form.')),
            ],
            options={
                'verbose_name': 'interest area',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JoinStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(default=True, help_text='Untick to hide this from the site.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers come first.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=80)),
                ('body', models.TextField()),
            ],
            options={
                'verbose_name': 'joining step',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(default=True, help_text='Untick to hide this from the site.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers come first.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('title', models.CharField(max_length=120)),
                ('eyebrow', models.CharField(blank=True, default='', help_text='Small line above the title.', max_length=120)),
                ('lead', models.TextField(help_text='The paragraph under the title. Also the meta description.')),
                ('layout', models.CharField(choices=[('document', 'Document, with a contents list in the margin'), ('plain', 'Plain, narrow column')], default='document', max_length=12)),
                ('show_version', models.BooleanField(default=False, help_text='Show the version and review date.')),
                ('version', models.CharField(blank=True, default='Version 1', max_length=20)),
                ('reviewed_on', models.DateField(blank=True, null=True)),
                ('intro', models.TextField(blank=True, default='', help_text='Optional paragraph before the first section.')),
                ('notice_title', models.CharField(blank=True, default='', help_text='Optional boxed note at the top. Leave blank for none.', max_length=120)),
                ('notice_body', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'page',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResourceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(default=True, help_text='Untick to hide this from the site.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers come first.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('heading', models.CharField(max_length=120)),
                ('anchor', models.SlugField(blank=True, max_length=60)),
                ('body', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'resource group',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResponsibilityArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(default=True, help_text='Untick to hide this from the site.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers come first.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('subtitle', models.CharField(blank=True, default='', max_length=120)),
                ('bullets', content.models.BulletsField(help_text='One responsibility per line. Blank lines are ignored.')),
            ],
            options={
                'verbose_name': 'area of responsibility',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community_name', models.CharField(default='KDU Developer Community', max_length=80)),
                ('university', models.CharField(default='Kyungdong University', max_length=120)),
                ('country', models.CharField(default='South Korea', max_length=80)),
                ('founded', models.CharField(default='August 2026', max_length=40)),
                ('footer_blurb', models.TextField(default='A student-run developer community based at Kyungdong University, South Korea, open to students there and to any other developer.', help_text='Shown in the footer of every page.')),
                ('discord_url', models.URLField(blank=True, default='', help_text="Leave blank to show 'Soon'.")),
                ('whatsapp_url', models.URLField(blank=True, default='', help_text="Leave blank to show 'Soon'.")),
                ('instagram_url', models.URLField(blank=True, default='', help_text="Leave blank to show 'Soon'.")),
                ('github_url', models.URLField(blank=True, default='https://github.com/devcom-goseong')),
            ],
            options={
                'verbose_name': 'site settings',
                'verbose_name_plural': 'site settings',
            },
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(default=True, help_text='Untick to hide this from the site.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers come first.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=80)),
                ('body', models.TextField()),
            ],
            options={
                'verbose_name': 'value',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActivitySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=160)),
                ('body', models.TextField(blank=True, default='')),
                ('bullets', content.models.BulletsField(blank=True, default='', help_text='One bullet point per line. Blank lines are ignored.')),
                ('bullets_in_columns', models.BooleanField(default=False)),
                ('note_title', models.CharField(blank=True, default='', help_text='Turns this section into a boxed note.', max_length=120)),
                ('order', models.PositiveIntegerField(default=0)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='content.activity')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anchor', models.SlugField(blank=True, help_text='Used for the link in the contents list. Filled in from the heading if blank.', max_length=60)),
                ('heading', models.CharField(max_length=160)),
                ('body', models.TextField(blank=True, default='', help_text='One paragraph per blank-line-separated block.')),
                ('bullets', content.models.BulletsField(blank=True, default='', help_text='One bullet point per line. Blank lines are ignored.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='content.page')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(default=True, help_text='Untick to hide this from the site.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers come first.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('url', models.URLField()),
                ('note', models.CharField(blank=True, default='', help_text="Why it is worth someone's time.", max_length=200)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='content.resourcegroup')),
            ],
            options={
                'verbose_name': 'resource',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
    ]
